{
    'name': 'ct_report_v15',
    'version': '15.0',
    'category': '',
    'sequence': 1,
    'summary': 'Report',
    'author': 'Oretta Incorporation',
    'maintainer': 'Oretta Incorporation',
    'company': 'Oretta Incorporation',
    'depends': ['base','ct_function_v15'],
    'data': [  

        'security/ir.model.access.csv',
        'security/security_group.xml',
        'report/report_menu.xml',
        'report/utensils_report.xml',
        'report/manager_report.xml',
        'report/production_report.xml',
        'report/function_wise_recipes.xml',
        'report/ingredients_report.xml',
        'report/ingredients_report_details.xml',
        'report/in_house_vender_report.xml',
        'report/name_get_fuction_report.xml',
        'report/vendor_confirmation_from.xml',
        'report/con_in_house_and_service_report.xml',
        'report/feedback_report.xml',
        'report/lead_funtion_report.xml',
        'report/print_report.xml',
        'report/quotation_print_report.xml',
        'report/vender_service_report.xml',
        'report/vender_addons_report.xml',
        'report/vender_in_house_out_source_report.xml',
        'report/paper_formate.xml',
        'report/ledger_report.xml',
        'report/outstanding_report.xml',
        'report/costing_report.xml',
        'report/cancel_report.xml',
        'wizard/purches_all_po.xml',
        'wizard/menu_report.xml',
        'wizard/utensils_report_wiz.xml',
        'wizard/all_manager_report.xml',
        'wizard/all_production_report.xml',
        'wizard/ingredient_report.xml',
        'wizard/in_house_vender_report.xml',
        'wizard/function_wise_recipes_report.xml',
        'wizard/name_get_report_wiz.xml',
        'wizard/vender_confirmation_from.xml',
        'wizard/confirm_in_house_service_report.xml',
        'wizard/party_wise.xml',
        'wizard/item_wise.xml',
        'wizard/rm_with_category.xml',
        'view/party_wise_report.xml',
        'view/item_wise_report.xml',
        'view/rm_with_category_report.xml',
        'wizard/feed_back_form_report.xml',
        'wizard/order_report.xml',  
        'wizard/vender_report.xml',  
        'view/home.xml',
        'view/ledger_form.xml',
        'view/outstanding.xml',
        'view/costing.xml',
        'view/cancel.xml',
        'view/main_menu.xml',
          ],    
    'assets': {
        'web.assets_qweb': [
            # "ct_report_v15/view/home.xml",
            "ct_report_v15/static/xml/cust_dashboard.xml",
        ],
        'web.assets_backend': [
            "ct_report_v15/static/js/cust_home.js"
        ],
         "web.report_assets_pdf": [
            "/ct_report_v15/static/src/css/report_qweb_pdf_watermark.css"
        ],
    },
    'installable': True,
    'application':True,
    'auto_install': False
}