{
    'name': 'ct_function_v15',
    'version': '15.0',
    'category': '',
    'sequence': 1,
    'summary': 'Master',
    'author': 'Oretta Incorporation',
    'maintainer': 'Oretta Incorporation',
    'company': 'Oretta Incorporation',
    'depends': ['base','contacts','web','ct_inventory_v15','account','sale_management','purchase','calendar','sale','web','calendar'],
    'data': [  
        'security/ir.model.access.csv',
        'security/security.xml',
        'data/data.xml',
        'data/sequence.xml',
        'data/mail_template_data.xml',
        'wizards/add_utensils.xml',
        'wizards/out_source_and_in_house_po.xml',
        'wizards/addons_line_wizard.xml',
        'wizards/fetch_menu.xml',
        'wizards/service_line_wizard.xml',
        'wizards/print.xml',  
        'wizards/recipes_rm_wiz.xml',
        'wizards/ct_purchase_wiz.xml',
        'wizards/in_house_bill_wiz.xml',
        'wizards/email.xml',
        'wizards/issue_return.xml',
        'wizards/sale_bill_customer_wiz.xml',
        'wizards/cancel_wizard.xml',
        'wizards/edit_function.xml',
        'wizards/all_po_prints.xml',
        'wizards/done_activity_view.xml',
        'report/all_po_prints.xml',
        'report/paper_formate.xml',
        'report/raw_material_view.xml',
        'report/raw_material_report.xml',
        'report/out_source_view.xml',
        'report/in_house_view.xml',
        'report/service_view.xml',
        'report/addons_view.xml',
        'report/saleorder_report_template.xml',
        'report/po_print.xml',
        'report/invoice_print.xml',
        'report/meeting_prints.xml',
        'view/fuction_mst.xml',
        'view/inherit_purchase.xml',
        'view/fuction.xml',
        'view/ct_hospitality_shift.xml',
        'view/utensils_view.xml',
        'view/inherit_account_move.xml',
        'view/lead.xml',
        'view/inherit_calender.xml',
        'view/inherit_sale.xml',
        'view/inherit_stock_packing.xml',
        'view/hop_calendar.xml',
        'view/meeting.xml',
        'view/cancel_report.xml',
        'view/transfer.xml',
        'view/opening_stock.xml',
        'view/config.xml',  
        'view/account_payment.xml',
        # 'view/main_menu.xml'
          ],    
    'assets': {
        'web.assets_qweb': [
            'ct_function_v15/static/src/**/*.xml',
        ],
        'web.assets_backend': [
            'ct_function_v15/static/src/css/style.css',
        ]
    },
    'installable': True,
    'application':True,
    'auto_install': False
}
